CREATE TABLE users(
userID INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL,
password TEXT NOT NULL,
email TEXT);

CREATE TABLE calculator(
calculatorID INTEGER PRIMARY KEY AUTOINCREMENT,
calculatorDat TEXT NOT NULL,
userID INT NOT NULL,
FOREIGN KEY(userID) REFERENCES users(userID)
ON DELETE CASCADE);

CREATE TABLE goal(
goalID INTEGER PRIMARY KEY AUTOINCREMENT,
goalDat TEXT NOT NULL,
userID INT NOT NULL,
FOREIGN KEY(userID) REFERENCES users(userID)
ON DELETE CASCADE);

CREATE TABLE goallist(
goallistID INTEGER PRIMARY KEY AUTOINCREMENT,
goallistDat TEXT NOT NULL,
userID INT NOT NULL,
FOREIGN KEY(userID) REFERENCES users(userID)
ON DELETE CASCADE);
